local tactics = {
	{
		id = 1, 
		name = "主攻左路", 
		type = 0, 
		attack_left = 20, 
		attack_right = 0, 
		attack_middle = 0, 
		defence_left = 0, 
		defence_right = 0, 
		defence_middle = 0, 
	},
	{
		id = 2, 
		name = "主攻右路", 
		type = 0, 
		attack_left = 0, 
		attack_right = 20, 
		attack_middle = 0, 
		defence_left = 0, 
		defence_right = 0, 
		defence_middle = 0, 
	},
	{
		id = 3, 
		name = "主攻中路", 
		type = 0, 
		attack_left = 0, 
		attack_right = 0, 
		attack_middle = 20, 
		defence_left = 0, 
		defence_right = 0, 
		defence_middle = 0, 
	},
	{
		id = 4, 
		name = "两翼齐飞", 
		type = 0, 
		attack_left = 10, 
		attack_right = 10, 
		attack_middle = 0, 
		defence_left = 0, 
		defence_right = 0, 
		defence_middle = 0, 
	},
	{
		id = 5, 
		name = "中路渗透", 
		type = 0, 
		attack_left = 5, 
		attack_right = 5, 
		attack_middle = 10, 
		defence_left = 0, 
		defence_right = 0, 
		defence_middle = 0, 
	},
	{
		id = 6, 
		name = "主防左路", 
		type = 1, 
		attack_left = 0, 
		attack_right = 0, 
		attack_middle = 0, 
		defence_left = 20, 
		defence_right = 0, 
		defence_middle = 0, 
	},
	{
		id = 7, 
		name = "主防右路", 
		type = 1, 
		attack_left = 0, 
		attack_right = 0, 
		attack_middle = 0, 
		defence_left = 0, 
		defence_right = 20, 
		defence_middle = 0, 
	},
	{
		id = 8, 
		name = "主防中路", 
		type = 1, 
		attack_left = 0, 
		attack_right = 0, 
		attack_middle = 0, 
		defence_left = 0, 
		defence_right = 0, 
		defence_middle = 20, 
	},
	{
		id = 9, 
		name = "两翼齐防", 
		type = 1, 
		attack_left = 0, 
		attack_right = 0, 
		attack_middle = 0, 
		defence_left = 10, 
		defence_right = 10, 
		defence_middle = 0, 
	},
	{
		id = 10, 
		name = "中路堵防", 
		type = 1, 
		attack_left = 0, 
		attack_right = 0, 
		attack_middle = 0, 
		defence_left = 5, 
		defence_right = 5, 
		defence_middle = 10, 
	},
}


return tactics